const expenses = [
  {
    id: 1,
    title: 'Apple',
    category: 'Groceries',
    paid_by: 'cash',
    amount: 100,
    createdAt: '2023-01-01',
  },
  {
    id: 2,
    title: 'Oranges',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 50,
    createdAt: '2023-01-01',
  },
  {
    id: 3,
    title: 'Bhindi',
    category: 'Groceries',
    paid_by: 'upi',
    amount: 14,
    createdAt: '2023-01-01',
  },
  {
    id: 4,
    title: 'Carrots',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 5,
    createdAt: '2023-01-01',
  },
  {
    id: 5,
    title: 'Cabbage',
    category: 'Groceries',
    paid_by: 'upi',
    amount: 35,
    createdAt: '2023-01-01',
  },
  {
    id: 6,
    title: 'Water Melon',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 55,
    createdAt: '2023-01-01',
  },
  {
    id: 7,
    title: 'Apple',
    category: 'Groceries',
    paid_by: 'cash',
    amount: 100,
    createdAt: '2023-01-01',
  },
  {
    id: 8,
    title: 'Oranges',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 50,
    createdAt: '2023-01-01',
  },
  {
    id: 9,
    title: 'Bhindi',
    category: 'Groceries',
    paid_by: 'upi',
    amount: 14,
    createdAt: '2023-01-01',
  },
  {
    id: 10,
    title: 'Carrots',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 5,
    createdAt: '2023-01-01',
  },
  {
    id: 11,
    title: 'Cabbage',
    category: 'Groceries',
    paid_by: 'upi',
    amount: 35,
    createdAt: '2023-01-01',
  },
  {
    id: 12,
    title: 'Water Melon',
    category: 'Groceries',
    paid_by: 'cc',
    amount: 55,
    createdAt: '2023-01-01',
  },
];

export default expenses;
